---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: healthcheck

- name: "Create checkout directory"
  file:
    path: "{{ tmp_dir }}/healthcheck"
    state: directory
    mode: 0755
  tags: healthcheck

- name: "Clone git repo"
  git:
    repo: "{{ healthcheck_git_url }}"
    dest: "{{ tmp_dir }}/healthcheck"
  tags: healthcheck

- name: "Install Healthcheck"
  shell: "kubectl apply -f {{ tmp_dir }}/healthcheck/kubernetes/"
  tags: healthcheck

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: healthcheck
